config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'admin/home'

  root to: 'kashkulistan#index'

  get 'admin' => 'admin#home'

  #API Routes, used for Axios requests from Vue app
  namespace :api, defaults: { format: :json } do
  	namespace :v1 do
    	resources :people, only: [ :index ]
    	resources :events, only: [ :index ]
    	resources :projects, only: [ :index ]
    end
  end

  #Rails app routes, used for CMS
  resources :projects
  resources :people

end  

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
  
end

app/models/event.rb
class Event < ApplicationRecord
	
end

app/models/person.rb
class Person < ApplicationRecord
	#photo uploader using carrierwave
	mount_uploader :photo, PersonPhotoUploader

	def self.group_by_category(array_of_categories)
		#define empty array for all people
		people_array = []
		#Loop through inputted categories, making an array for each and adding it to the people_array
		array_of_categories.each do |category|
			people_array << make_categorized_array(category)
		end
		return people_array
	end

	private
	def self.make_categorized_array(category)
		categorized_array = []
		category_members = find_by_category(category)
		category_members.each do |member|
			categorized_array << member
		end
		return categorized_array
	end

	def self.find_by_category(category)
		category_members = self.where(category: category)
		return category_members
	end
end

app/models/project.rb
class Project < ApplicationRecord

	#photo uploader using carrierwave
	mount_uploader :photo, ProjectPhotoUploader

	#This method splits all projects into two groups
	#grouping allows frontend Vue app to easily format into columns.
	def self.make_columns
		#select all projects
		projects = self.all
		#Make array with all projects
		projects_array = []
		projects.each do |project|
			projects_array << project
		end
		#Take projects array, and split into two sub arrays
		grouped_array = projects_array.each_slice( (projects_array.size/2.0).round ).to_a
	end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_admin!
	layout 'cmslayout'

  def home
  end

end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApplicationController
	def index
		@events = Event.all
		render json: @events
	end
end

app/controllers/api/v1/people_controller.rb
class Api::V1::PeopleController < ApplicationController
	def index
		#This returns all people in the database, grouped by assigned category.
		@people = Person.group_by_category(['Researcher', 'Visiting', 'Director'])
		render json: @people
	end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < ApplicationController
		def index
		#Divide all projects into two sets for column formatting in Vue app.
		@projects = Project.make_columns
		render json: @projects
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kashkulistan_controller.rb
class KashkulistanController < ApplicationController
  def index
  	#This just launches the Kashkulistan Vue app -> see app/javascript/packs/kashkulistan.js
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	layout 'cmslayout'
	before_action :authenticate_admin!, :find_person, only: [:show, :edit, :update, :destroy]
	
	def index
		@people = Person.order("id ASC")
	end

	def new
		@person = Person.new
	end

	def create
		@person = Person.new(person_params)
		if @person.save
			redirect_to people_path, notice: "Person created"
		else
			render 'new'
		end
	end

	def edit
	end

	def show
	end

	def update
		if @person.update(person_params)
			redirect_to @person, notice: "Person updated"
		else
			render 'edit'
		end
	end

	def destroy
    @person.destroy
    redirect_to people_path, notice: "Person deleted"
	end

	private

	def person_params
		params.require(:person).permit(:name, :role, :about, :photo, :category)
	end

	def find_person
		@person = Person.find(params[:id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	layout 'cmslayout'
	before_action :authenticate_admin!, :find_project, only: [:show, :edit, :update, :destroy]
	
	def index
		@projects = Project.order("id ASC")
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			redirect_to @project, notice: "Project created"
		else
			render 'new'
		end
	end

	def edit
	end

	def show
	end

	def update
		if @project.update(project_params)
			redirect_to @project, notice: "Project updated"
		else
			render 'edit'
		end
	end

	def destroy
    @project.destroy
    redirect_to projects_path, notice: "Project deleted"
	end

	private

	def project_params
		params.require(:project).permit(:name, :description, :authors, :url, :photo)
	end

	def find_project
		@project = Project.find(params[:id])
	end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api/v1/events_helper.rb
module Api::V1::EventsHelper
end

app/helpers/api/v1/people_helper.rb
module Api::V1::PeopleHelper
end

app/helpers/api/v1/projects_helper.rb
module Api::V1::ProjectsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/home.html.erb
<h1>Admin#home</h1>
<p>Find me in app/views/admin/home.html.erb</p>

app/views/kashkulistan/index.html.erb
<!-- Launches Kashkulistan Vue app -> see app/javascript/packs/kashkulistan.js -->

<%= javascript_pack_tag 'kashkulistan' %>
<%= stylesheet_pack_tag 'kashkulistan' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kashkul</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="margin: 0">
    <%= yield %>
  </body>
</html>

app/views/layouts/cmslayout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kashkulistan</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

  </head>

  <body style="margin: 0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to("projects", projects_path, class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to("people", people_path, class: "nav-link") %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <% if admin_signed_in? %>
            <%= link_to('Logout', destroy_admin_session_path, class: "navbar-right") %>
          <% end %>
        </li>
      </ul>
    </nav>
  	<main class="container">
    		<%= yield %>
    </div>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for @person, html: { multipart: true, class: "form-horizontal center" } do |f| %>
	<div class="form-group">
		<%= f.label :name %><br>
		<%= f.text_field :name, class: "form-control" %><br>	
	</div>
	<div class="form-group">
		<%= f.label :role %><br>
		<%= f.text_field :role, class: "form-control" %><br>
	</div>
	<div class="form-group">
		<%= f.label :category %><br>
		<%= f.select(:category, options_for_select([['Researcher', 'Researcher'], ['Visiting Scholar/Artist', 'Visiting'], ['Director', 'Director']]), class: "form-control") %><br>
	</div>
	<div class="form-group">
		<%= f.label :about %><br>
		<%= f.text_area :about, class: "form-control" %><br>	
	</div>	
	<div class="form-group">
		<%= f.label :photo %><br>
		<%= f.file_field :photo %><br>
	</div>

	<%= f.submit %>
	<%= button_to "cancel", people_path %>

<% end %>

app/views/people/edit.html.erb
<%= link_to "Back to people", people_path %>
<h1>Edit Person:</h1>
<%= render partial: "form" %>

app/views/people/index.html.erb
<div class="container">
  <div class="col-sm-10 col-sm-offset-1 col-xs-12 blog-content">
    <% @people.each do |person| %>
    <div class="col-xs-12">
      <div class="text-center">
        <%= link_to( person.name, person_path(person) ) %>
      </div>
      <br>
    </div>
    <% end %>
  </div>
  <%= link_to("New Person", new_person_path) %>
</div>

app/views/people/new.html.erb
<%= link_to "Back to people", people_path %>
<h1>New Person:</h1>
<%= render partial: "form" %>

app/views/people/show.html.erb
<%= link_to "Back to people", people_path %>
<h1><%=@person.name%></h1>
<%= image_tag(@person.photo_url.to_s) %>
<p>Role: <%=@person.role%></p>
<p>About: <%=@person.about%></p>

<%= link_to "Edit", edit_person_path(@person) %>
<br>
<%= link_to "Delete", person_path(@person), 
											method: :delete, 
											data: { confirm: "Are you sure you want to delete this person?" } %>

app/views/projects/_form.html.erb
<%= form_for @project, html: { multipart: true, class: "form-horizontal center" } do |f| %>
	<div class="form-group">
		<%= f.label :name %><br>
		<%= f.text_field :name, class: "form-control" %><br>	
	</div>
	<div class="form-group">
		<%= f.label :description %><br>
		<%= f.text_area :description, class: "form-control" %><br>
	</div>
	<div class="form-group">
		<%= f.label :authors %><br>
		<%= f.text_field :authors, class: "form-control" %><br>	
	</div>	
	<div class="form-group">
		<%= f.label :url %><br>
		<%= f.text_field :url, class: "form-control" %><br>	
	</div>
	<div class="form-group">
		<%= f.label :photo %><br>
		<%= f.file_field :photo %><br>
	</div>

	<%= f.submit %>
	<%= button_to "cancel", people_path %>

<% end %>

app/views/projects/edit.html.erb
<%= link_to "Back to Projects", projects_path %>
<h1>Edit Project:</h1>
<%= render partial: "form" %>

app/views/projects/index.html.erb
<div class="container">
  <div class="col-sm-10 col-sm-offset-1 col-xs-12 blog-content">
    <% @projects.each do |project| %>
    <div class="col-xs-12">
      <div class="text-center">
        <%= link_to( project.name, project_path(project) ) %>
      </div>
      <br>
    </div>
    <% end %>
  </div>
  <%= link_to("New Project", new_project_path) %>
</div>

app/views/projects/new.html.erb
<%= link_to "Back to Projects", projects_path %>
<h1>New Project:</h1>
<%= render partial: "form" %>

app/views/projects/show.html.erb
<h1><%=@project.name%></h1>
<p>Description: <%=@project.description%></p>
<%= image_tag(@project.photo_url.to_s) %>
<p><%=@project.authors%></p>

<%= link_to "Edit", edit_project_path(@project) %>
<br>
<%= link_to "Delete", project_path(@project), 
											method: :delete, 
											data: { confirm: "Are you sure you want to delete this project?" } %>